### ISSUE TITLE
시간대 밝기 오류

### ISSUE THREAD

**Issue by pdom0327** [Ciart/Pagomoa#119]
- 밤에 시작 시 어둡지 않음
- 저녁에 점점 어두워져야하는데 점점 밝아짐

**Comment by cksuwjr** [comment]
Fixed #129

**Comment by cksuwjr** [comment]
a ~ b 까지 a에서 b로 변한다고 가정할 때 (a는 시작값, b는 최후값)

Default(변화 전):  a
Start(변화 시작): a + ( b - a ) * 변화시간

ex)   0.2 ~ 1
Start = 0.2 + 0.8 * (시간 변화시간) = 0.2 0.2 0.2  ...  ...  0.2  ...  0.36 ...  0.52  ... 1
