### ISSUE TITLE
키보드에 따른 Dig 방향 버그

### ISSUE THREAD

**Issue by cksuwjr** [Ciart/Pagomoa#52]
키보드 방향키를 →↑ 누르며 땅을 팔 경우  다음과 같은 방향을 바라보며 바닥을 판다.
![image](https://github.com/Ciart/Pagomoa/assets/63836325/7b067074-322e-4a4d-8e86-1d867680b858)

왼쪽방향의 경우 문제 없다.

**Comment by pdom0327** [comment]
#57을 통해 개선될 것으로 보입니다.
