### ISSUE TITLE
특정 상황에서 맨 위로 올라갈 수 없는 문제

### ISSUE THREAD

**Issue by pdom0327** [Ciart/Pagomoa#71]
<img width="383" alt="image" src="https://github.com/Ciart/Pagomoa/assets/12953393/9942c0fd-d6cf-4fdc-90d6-62ed29200b8f">

한 칸짜리로 기어갈 수 없기 때문에 위로 올라갈 수 없음

**Comment by cksuwjr** [comment]
확인 후 닫아주세용
